site_name: Bitprim
site_url: http://www.bitprim.org
site_description: Bitprim
site_author: Bitprim Team

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: ""

pages:
    - Home: index.md
    - User Guide:
        - Installation: Installation.md
        - Extensions Blocks: Extension-blocks.md
        - LBNet: LBNet.md
        - Mining Engine: Mining-engine.md
        - Modules Messaging: Modules-messaging.md
        - Sql: Primitive-sql.md
        - Real Consensus: Real-consensus.md
        - RPC: RPC-Support.md
    - Developer Guide:
        - .Net: .Net-Interface.md
            - Reference: Dotnet-interface-details.md
        - C:
        - C++:
        - Go:
        - Python:    
    - About:
        - Team: Team.md
        

copyright: Copyright &copy; 2018 Bitprim

plugins:
    - search    