site_name: Bitprim
site_url: http://www.bitprim.org
site_description: Bitprim
site_author: Bitprim Team

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: ""

pages:
    - Home: index.md
    - User Guide:
        - Introduction:  
        - Getting Started: 
        - Installation: Installation.md
        - FAQ: 
        - Release Notes: 
    - Developer Guide:
        - Introduction: 
        - Tutorials: 
        - .Net: 
            - Introduction: .Net-Interface.md
            - Reference: Dotnet-interface-details.md
        - C:
        - C++:
        - Python:
        - Go:
        - Javascript:    
    - About:
        - Team: Team.md
        
copyright: Copyright &copy; 2018 Bitprim

plugins:
    - search    