site_name: Bitprim
site_url: http://www.bitprim.org
site_description: Bitprim
site_author: Bitprim Team

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: ""

pages:
    - Home: index.md
    - User Guide:
        - Introduction: blank.md 
        - Getting Started: blank.md
        - Installation: Installation.md
        - FAQ: blank.md
        - Release Notes: blank.md 
    - Developer Guide:
        - Introduction: blank.md
        - Tutorials: blank.md
        - .Net: 
            - Introduction: .Net-Interface.md
            - Reference: Dotnet-interface-details.md
        - C: blank.md
        - C++: blank.md
        - Python: blank.md
        - Go: blank.md
        - Javascript: blank.md   
    - About:
        - Team: Team.md
        
copyright: Copyright &copy; 2018 Bitprim

plugins:
    - search    